### ISSUE TITLE
pytribe firmware update tool

### ISSUE THREAD

**Issue by sjobeek** [sradevski/EyeTribe-Web-Socket-Server#1]
Hello, I hate to pollute your issues with this question, but I've run into issues getting my pytribe device running and believe i need to update my device firmware since its an early unit.

Does anyone on this team happen to have a copy of the firmware update tool they could send me, or know where i could find it?

**Comment by sradevski** [comment]
Hey! No problem at all, don't worry about it. Let me check once I get back from work, and I will let you know if I have the firmware. Cheers!

**Comment by sradevski** [comment]
Sorry for the late reply! It seems I don't have the firmware anymore (I don't have the EyeTribe anymore as well). I hope you will find it somewhere :)

**Comment by sjobeek** [comment]
No worries, thanks for checking
